ALTER TABLE users
    ALTER COLUMN is_deleted TYPE BOOLEAN
        USING (CASE WHEN is_deleted = 'Y' THEN TRUE ELSE FALSE END),
    ALTER COLUMN is_deleted SET DEFAULT FALSE;


ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP, ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMP, ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;