-- ALTER TABLE users ALTER COLUMN is_deleted TYPE BOOLEAN, ALTER COLUMN is_deleted SET DEFAULT FALSE;
-- ALTER TABLE alcohols DROP COLUMN tasting_note_id;
ALTER TABLE alcohols ADD COLUMN "wish_cnt" INTEGER NOT NULL DEFAULT 0;
-- ALTER TABLE users ALTER COLUMN is_deleted TYPE BOOLEAN, ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE alcohols DROP COLUMN IF EXISTS wish;